# Generated by Django 4.2.7 on 2024-01-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject1', '0002_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_time',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
